### ISSUE TITLE
Docker build once deploy anywhere

### ISSUE THREAD

**Issue by emanuelcoelho1986** [PatrickJS/angular-starter#2011]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @TipeIO](https://twitter.com/TipeIO)

* **I'm submitting a ...**
[ ] bug report
[ x] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I would like to request a feature, if possible. The feature is a build once deploy anywhere.

* **What is the current behavior?**
Right now when we create a Docker image this image is for production only. It would be nice if we have a way to build once and deploy anywhere.

* **What is the motivation / use case for changing the behavior?**
I've been working with docker for a while and most of my projects now require the same code base different configurations. It might be a very specific case but I think this kind of behaviour with clients will increase. They want the project but after that they want different configurations. eg: Integrate their auth0 app clients. Now imagine this for each env, dev, stage, and then multiple lives. It would be a great feature to have. Build takes a lot of time to do and if we have a case of multiple production deploys with different configurations it will take ages.

**Comment by lanovoy** [comment]
This is how we do it: we have multiple configurations bundled with the application in form of json files. When we're running a container, we pass an environment variable with the name of the environment. Then the kestrel server in our case would serve when requested from client for config.json a content from the environment specific config that we have on the file system inside the image but not in the folder from where static files are served. In case if you're using nginx, for example and only statically serve files, then there is an option to create a script which will run prior to starting nginx in the container and which will rename config.<environment>.json to config.json for the current environment.

**Comment by emanuelcoelho1986** [comment]
Thanks for your answer Iavonoy. We did something similar. We are using Google Cloud and Circle CI. We did something similar. Upon deploys, after all the actions we mount a config folder with the desired configurations for the desired client. This was a way we found to have multiple clients with several configs.

Either way man, I thank you for your answer.

**Comment by lanovoy** [comment]
Yeah, that may be a good solution if you want to be able to change the configuration without rebuilding the image/redeploying the container...
